#@Value - Value Mapping
property:
    test:
      name: property depth test
propertyTest: test
propertyTestList: a,b,c

#ConfigurationProperties - Value Mapping(List, Map)
fruit:
  list:
    - name: banana
      color: yellow
    - name: apple
      color: red
    - name: water melon
      color: green