devtools:
  livereload:
    enabled: true

datasource:
  url: jdbc:h2:mem:testdb

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  security:
    oauth2:
     client:
       registration:
         google:
           client-id: 764246968315-u0cnjsdmhdrvpcgqbgllo5f9a08g4fn9.apps.googleusercontent.com
           client-secret: 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
         facebook:
           client-id: 629411522280442
           client-secret: a8734f4d297f899826ebf491379bb7f7
custom:
  oauth2:
    kakao:
      client-id: ee0cab12340a455a1ffaf00de433860d

#SNS 프로퍼티 바인딩
#
#facebook :
#  client :
#    clientId : 629411522280442
#    clientSecret: a8734f4d297f899826ebf491379bb7f7
#    accessTokenUri: https://graph.facebook.com/oauth/access_token
#    userAuthorizationUri: https://www.facebook.com/dialog/oauth?display=popup
#    tokenName: oauth_token
#    authenticationScheme: query
#    clientAuthenticationScheme: form
#    scope: email
#  resource:
#    userInfoUri: https://graph.facebook.com/me?fields=id,name,email,link
#
#google :
#  client :
#    clientId : 764246968315-u0cnjsdmhdrvpcgqbgllo5f9a08g4fn9.apps.googleusercontent.com
#    clientSecret: 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
#    accessTokenUri: https://accounts.google.com/o/oauth2/token
#    userAuthorizationUri: https://accounts.google.com/o/oauth2/auth
#    scope: email, profile
#  resource:
#    userInfoUri: https://www.googleapis.com/oauth2/v2/userinfo
#
#kakao :
#  client :
#    clientId : ee0cab12340a455a1ffaf00de433860d
#    accessTokenUri: https://kauth.kakao.com/oauth/token
#    userAuthorizationUri: https://kauth.kakao.com/oauth/authorize
#  resource:
#    userInfoUri: https://kapi.kakao.com/v1/user/me