devtools:
  livereload:
    enabled: true

datasource:
  url: jdbc:h2:mem:testdb

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  security:
    oauth2:
     client:
       registration:
         google:
           client-id: 
           client-secret: 
         facebook:
           client-id: 
           client-secret: 
custom:
  oauth2:
    kakao:
      client-id: 
